fix first non-dependent step of build-tag-and-publish

diff --git a/.github/workflows/build-tag-and-publish.yml b/.github/workflows/build-tag-and-publish.yml
--- a/.github/workflows/build-tag-and-publish.yml
+++ b/.github/workflows/build-tag-and-publish.yml
@@ -21,13 +21,18 @@ env:
 
 jobs:
   check:
-    name: Check workflow
+    name: Check workflow (and have one non-dependent job)
     runs-on: self-hosted
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-      - name: Check Python version
-        run: python --version
+      - name: Check for necessary files
+        run: |
+          if [ ! -f "pyproject.toml" ]; then
+            echo "pyproject.toml is missing"
+            exit 1
+          fi
+          echo "Build file is present"
 
   build:
     name: Build distribution 📦
